version: "3"
services:
  mysqldb:
    image: mysql:8.0.29
    ports:
      - "3307:3306"
    networks:
      - quizzz_springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=admin13
      - MYSQL_DATABASE=quizzz
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=admin13
  cache:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - quizzz_springmysql-net

  front-app:
    image: front:2.0 # 2.1 versija jungiasi viduje containerio su atitinakmais adresais, 2.0 versija per localhostus
    ports:
      - "83:80"
    networks:
      - quizzz_springmysql-net
    depends_on:
      - back-app

  back-app:
    image: back:1.6
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      spring_datasource_url: jdbc:mysql://mysqldb:3306/quizzz?allowPublicKeyRetrieval=true&useSSL=false
      spring_datasource_username: sa
      spring_datasource_password: admin13
      spring_redis_host: cache
      spring_redis_port: 6379
    networks:
      - quizzz_springmysql-net
    depends_on:
      - mysqldb
      - cache

networks:
  quizzz_springmysql-net: